addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo" % "0.5.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-less"      % "1.1.0")
addSbtPlugin("io.spray"         % "sbt-revolver"  % "0.7.2")
addSbtPlugin("org.scala-js"     % "sbt-scalajs"   % "0.6.4")
addSbtPlugin("me.lessis"        % "bintray-sbt"   % "0.3.0")